name: binder
channels:
  - pytorch
  - conda-forge
dependencies:
  - python=3.7.6
  - cudatoolkit=9.0
  - pytorch
  - torchvision
  - matplotlib==2.0.2
  - numpy==1.14.1
  - ipython==6.2.1
  - scikit-learn==0.19.1
