# This is the simplest action for launching a Github repo using VS Online
name: Launch repo on VS Online

on:
  watch:
    types: [started]

jobs:
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # This is the trigger for when *I* star a repo
    if: github.actor == github.event.repository.owner.login

    steps:
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    - run: |
        az account list --output table
